module Test.QuantumGatesParserTests

import Test.TestHelper

export
runQuantumGatesParseTests : IO ()
runQuantumGatesParseTests = do

    -- Test quantum gates type declarations
    runParseOkTest "src/Test/Fixtures/Good/Gates/id.lf"
                    "Id(q);"
                    "Id(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/x.lf"
                    "X(q);"
                    "X(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/y.lf"
                    "Y(q);"
                    "Y(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/z.lf"
                    "Z(q);"
                    "Z(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/h.lf" 
                    "H(q);"
                    "H(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/s.lf"
                    "S(q);"
                    "S(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sdg.lf"
                    "SDG(q);"
                    "SDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/t.lf"
                    "T(q);"
                    "T(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/tdg.lf"
                    "TDG(q);"
                    "TDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sx.lf"
                    "SX(q);"
                    "SX(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sxdg.lf"
                    "SXDG(q);"
                    "SXDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rx.lf"
                    "RX(1, q);"
                    "RX(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ry.lf"
                    "RY(1, q);"
                    "RY(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rz.lf"
                    "RZ(1, q);"
                    "RZ(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u1.lf"
                    "U1(1, q);"
                    "U1(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u2.lf"
                    "U2(1, 2, q);"
                    "U2(1, 2, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u3.lf"
                    "U3(1, 2, 3, q);"
                    "U3(1, 2, 3, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cnot.lf"
                    "CNOT(q0, q1);"
                    "CNOT(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cx.lf"
                    "CX(q0, q1);"
                    "CX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cy.lf"
                    "CY(q0, q1);"
                    "CY(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cz.lf"
                    "CZ(q0, q1);"
                    "CZ(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cs.lf"
                    "CS(q0, q1);"
                    "CS(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csdg.lf"
                    "CSDG(q0, q1);"
                    "CSDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ct.lf"
                    "CT(q0, q1);"
                    "CT(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ctdg.lf"
                    "CTDG(q0, q1);"
                    "CTDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csx.lf"
                    "CSX(q0, q1);"
                    "CSX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csxdg.lf"
                    "CSXDG(q0, q1);"
                    "CSXDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/crx.lf"
                    "CRX(1, q0, q1);"
                    "CRX(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cry.lf"
                    "CRY(1, q0, q1);"
                    "CRY(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/crz.lf"
                    "CRZ(1, q0, q1);"
                    "CRZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu1.lf"
                    "CU1(1, q0, q1);"
                    "CU1(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu2.lf"
                    "CU2(1, 2, q0, q1);"
                    "CU2(1, 2, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu3.lf"
                    "CU3(1, 2, 3, q0, q1);"
                    "CU3(1, 2, 3, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/swap.lf"
                    "SWAP(q0, q1);"
                    "SWAP(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rxx.lf"
                    "RXX(1, q0, q1);"
                    "RXX(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ryy.lf"
                    "RYY(1, q0, q1);"
                    "RYY(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rzz.lf"
                    "RZZ(1, q0, q1);"
                    "RZZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ccx.lf"
                    "CCX(q0, q1, q2);"
                    "CCX(q0, q1, q2);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cswap.lf"
                    "CSWAP(q0, q1, q2);"
                    "CSWAP(q0, q1, q2);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/gpi.lf"
                    "GPI(1, q);"
                    "GPI(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/gpi2.lf"
                    "GPI2(1, q);"
                    "GPI2(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ms.lf"
                    "MS(1, 2, q0, q1);"
                    "MS(1, 2, q0, q1);"
                    
    -- Test quantum gates declarations corner cases
    runParseOkTest "src/Test/Fixtures/Good/Gates/noSpacesSingleQubitGate.lf"
                    "H(q);"
                    "H(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/extraWhitespaceSingleQubitGate.lf"
                    "SDG(q);"
                    "SDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/noSpacesTwoQubitGate.lf"
                    "CX(q0, q1);"
                    "CX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/extraWhitespaceTwoQubitGate.lf"
                    "SWAP(q0, q1);"
                    "SWAP(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/noSpacesParametricGate.lf"
                    "RX(1, q);"
                    "RX(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/extraWhitespaceParametricGate.lf"
                    "CU3(1, 2, 3, q0, q1);"
                    "CU3(1, 2, 3, q0, q1);"

    -- Test invalid quantum gates declarations
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingClosingParenInSingleQubitGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingArgumentSeparatorInSingleQubitGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingCommaInTwoQubitGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingClosingParenInTwoQubitGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingCommaInParametricGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingMiddleParameterInParametricGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingClosingParenInParametricGate.lf"