module Test.QuantumGatesParserTests

import Test.TestHelper

export
runQuantumGatesParseTests : IO ()
runQuantumGatesParseTests = do

    -- Test quantum gates type declarations
    runParseOkTest "src/Test/Fixtures/Good/Gates/id.lf"
                    "Id(q);"
                    "Id(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/idLet.lf"
                    "let q : qubit = Id(q);"
                    "let q : qubit = Id(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/idLetInferred.lf"
                    "let q = Id(q);"
                    "let q = Id(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/x.lf"
                    "X(q);"
                    "X(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/xLet.lf"
                    "let q : qubit = X(q);"
                    "let q : qubit = X(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/xLetInferred.lf"
                    "let q = X(q);"
                    "let q = X(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/y.lf"
                    "Y(q);"
                    "Y(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/yLet.lf"
                    "let q : qubit = Y(q);"
                    "let q : qubit = Y(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/yLetInferred.lf"
                    "let q = Y(q);"
                    "let q = Y(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/z.lf"
                    "Z(q);"
                    "Z(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/zLet.lf"
                    "let q : qubit = Z(q);"
                    "let q : qubit = Z(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/zLetInferred.lf"
                    "let q = Z(q);"
                    "let q = Z(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/h.lf" 
                    "H(q);"
                    "H(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/hLet.lf"
                    "let q : qubit = H(q);"
                    "let q : qubit = H(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/hLetInferred.lf"
                    "let q = H(q);"
                    "let q = H(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/s.lf"
                    "S(q);"
                    "S(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sLet.lf"
                    "let q : qubit = S(q);"
                    "let q : qubit = S(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sLetInferred.lf"
                    "let q = S(q);"
                    "let q = S(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sdg.lf"
                    "SDG(q);"
                    "SDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sdgLet.lf"
                    "let q : qubit = SDG(q);"
                    "let q : qubit = SDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sdgLetInferred.lf"
                    "let q = SDG(q);"
                    "let q = SDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/t.lf"
                    "T(q);"
                    "T(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/tLet.lf"
                    "let q : qubit = T(q);"
                    "let q : qubit = T(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/tLetInferred.lf"
                    "let q = T(q);"
                    "let q = T(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/tdg.lf"
                    "TDG(q);"
                    "TDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/tdgLet.lf"
                    "let q : qubit = TDG(q);"
                    "let q : qubit = TDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/tdgLetInferred.lf"
                    "let q = TDG(q);"
                    "let q = TDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sx.lf"
                    "SX(q);"
                    "SX(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sxLet.lf"
                    "let q : qubit = SX(q);"
                    "let q : qubit = SX(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sxLetInferred.lf"
                    "let q = SX(q);"
                    "let q = SX(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sxdg.lf"
                    "SXDG(q);"
                    "SXDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sxdgLet.lf"
                    "let q : qubit = SXDG(q);"
                    "let q : qubit = SXDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/sxdgLetInferred.lf"
                    "let q = SXDG(q);"
                    "let q = SXDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rx.lf"
                    "RX(1, q);"
                    "RX(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rxLet.lf"
                    "let q : qubit = RX(1, q);"
                    "let q : qubit = RX(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rxLetInferred.lf"
                    "let q = RX(1, q);"
                    "let q = RX(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ry.lf"
                    "RY(1, q);"
                    "RY(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ryLet.lf"
                    "let q : qubit = RY(1, q);"
                    "let q : qubit = RY(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ryLetInferred.lf"
                    "let q = RY(1, q);"
                    "let q = RY(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rz.lf"
                    "RZ(1, q);"
                    "RZ(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rzLet.lf"
                    "let q : qubit = RZ(1, q);"
                    "let q : qubit = RZ(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rzLetInferred.lf"
                    "let q = RZ(1, q);"
                    "let q = RZ(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u1.lf"
                    "U1(1, q);"
                    "U1(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u1Let.lf"
                    "let q : qubit = U1(1, q);"
                    "let q : qubit = U1(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u1LetInferred.lf"
                    "let q = U1(1, q);"
                    "let q = U1(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u2.lf"
                    "U2(1, 2, q);"
                    "U2(1, 2, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u2Let.lf"
                    "let q : qubit = U2(1, 2, q);"
                    "let q : qubit = U2(1, 2, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u2LetInferred.lf"
                    "let q = U2(1, 2, q);"
                    "let q = U2(1, 2, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u3.lf"
                    "U3(1, 2, 3, q);"
                    "U3(1, 2, 3, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u3Let.lf"
                    "let q : qubit = U3(1, 2, 3, q);"
                    "let q : qubit = U3(1, 2, 3, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/u3LetInferred.lf"
                    "let q = U3(1, 2, 3, q);"
                    "let q = U3(1, 2, 3, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cnot.lf"
                    "CNOT(q0, q1);"
                    "CNOT(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cnotLet.lf"
                    "let qs : [qubit; 2] = CNOT(q0, q1);"
                    "let qs : [qubit; 2] = CNOT(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cnotLetInferred.lf"
                    "let qs = CNOT(q0, q1);"
                    "let qs = CNOT(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cx.lf"
                    "CX(q0, q1);"
                    "CX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cxLet.lf"
                    "let qs : [qubit; 2] = CX(q0, q1);"
                    "let qs : [qubit; 2] = CX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cxLetInferred.lf"
                    "let qs = CX(q0, q1);"
                    "let qs = CX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cy.lf"
                    "CY(q0, q1);"
                    "CY(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cyLet.lf"
                    "let qs : [qubit; 2] = CY(q0, q1);"
                    "let qs : [qubit; 2] = CY(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cyLetInferred.lf"
                    "let qs = CY(q0, q1);"
                    "let qs = CY(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cz.lf"
                    "CZ(q0, q1);"
                    "CZ(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/czLet.lf"
                    "let qs : [qubit; 2] = CZ(q0, q1);"
                    "let qs : [qubit; 2] = CZ(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/czLetInferred.lf"
                    "let qs = CZ(q0, q1);"
                    "let qs = CZ(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cs.lf"
                    "CS(q0, q1);"
                    "CS(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csLet.lf"
                    "let qs : [qubit; 2] = CS(q0, q1);"
                    "let qs : [qubit; 2] = CS(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csLetInferred.lf"
                    "let qs = CS(q0, q1);"
                    "let qs = CS(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csdg.lf"
                    "CSDG(q0, q1);"
                    "CSDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csdgLet.lf"
                    "let qs : [qubit; 2] = CSDG(q0, q1);"
                    "let qs : [qubit; 2] = CSDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csdgLetInferred.lf"
                    "let qs = CSDG(q0, q1);"
                    "let qs = CSDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ct.lf"
                    "CT(q0, q1);"
                    "CT(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ctLet.lf"
                    "let qs : [qubit; 2] = CT(q0, q1);"
                    "let qs : [qubit; 2] = CT(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ctLetInferred.lf"
                    "let qs = CT(q0, q1);"
                    "let qs = CT(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ctdg.lf"
                    "CTDG(q0, q1);"
                    "CTDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ctdgLet.lf"
                    "let qs : [qubit; 2] = CTDG(q0, q1);"
                    "let qs : [qubit; 2] = CTDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ctdgLetInferred.lf"
                    "let qs = CTDG(q0, q1);"
                    "let qs = CTDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csx.lf"
                    "CSX(q0, q1);"
                    "CSX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csxLet.lf"
                    "let qs : [qubit; 2] = CSX(q0, q1);"
                    "let qs : [qubit; 2] = CSX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csxLetInferred.lf"
                    "let qs = CSX(q0, q1);"
                    "let qs = CSX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csxdg.lf"
                    "CSXDG(q0, q1);"
                    "CSXDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csxdgLet.lf"
                    "let qs : [qubit; 2] = CSXDG(q0, q1);"
                    "let qs : [qubit; 2] = CSXDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/csxdgLetInferred.lf"
                    "let qs = CSXDG(q0, q1);"
                    "let qs = CSXDG(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/crx.lf"
                    "CRX(1, q0, q1);"
                    "CRX(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/crxLet.lf"
                    "let qs : [qubit; 2] = CRX(1, q0, q1);"
                    "let qs : [qubit; 2] = CRX(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/crxLetInferred.lf"
                    "let qs = CRX(1, q0, q1);"
                    "let qs = CRX(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cry.lf"
                    "CRY(1, q0, q1);"
                    "CRY(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cryLet.lf"
                    "let qs : [qubit; 2] = CRY(1, q0, q1);"
                    "let qs : [qubit; 2] = CRY(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cryLetInferred.lf"
                    "let qs = CRY(1, q0, q1);"
                    "let qs = CRY(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/crz.lf"
                    "CRZ(1, q0, q1);"
                    "CRZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/crzLet.lf"
                    "let qs : [qubit; 2] = CRZ(1, q0, q1);"
                    "let qs : [qubit; 2] = CRZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/crzLetInferred.lf"
                    "let qs = CRZ(1, q0, q1);"
                    "let qs = CRZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu1.lf"
                    "CU1(1, q0, q1);"
                    "CU1(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu1Let.lf"
                    "let qs : [qubit; 2] = CU1(1, q0, q1);"
                    "let qs : [qubit; 2] = CU1(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu1LetInferred.lf"
                    "let qs = CU1(1, q0, q1);"
                    "let qs = CU1(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu2.lf"
                    "CU2(1, 2, q0, q1);"
                    "CU2(1, 2, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu2Let.lf"
                    "let qs : [qubit; 2] = CU2(1, 2, q0, q1);"
                    "let qs : [qubit; 2] = CU2(1, 2, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu2LetInferred.lf"
                    "let qs = CU2(1, 2, q0, q1);"
                    "let qs = CU2(1, 2, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu3.lf"
                    "CU3(1, 2, 3, q0, q1);"
                    "CU3(1, 2, 3, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu3Let.lf"
                    "let qs : [qubit; 2] = CU3(1, 2, 3, q0, q1);"
                    "let qs : [qubit; 2] = CU3(1, 2, 3, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cu3LetInferred.lf"
                    "let qs = CU3(1, 2, 3, q0, q1);"
                    "let qs = CU3(1, 2, 3, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/swap.lf"
                    "SWAP(q0, q1);"
                    "SWAP(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/swapLet.lf"
                    "let qs : [qubit; 2] = SWAP(q0, q1);"
                    "let qs : [qubit; 2] = SWAP(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/swapLetInferred.lf"
                    "let qs = SWAP(q0, q1);"
                    "let qs = SWAP(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rxx.lf"
                    "RXX(1, q0, q1);"
                    "RXX(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rxxLet.lf"
                    "let qs : [qubit; 2] = RXX(1, q0, q1);"
                    "let qs : [qubit; 2] = RXX(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rxxLetInferred.lf"
                    "let qs = RXX(1, q0, q1);"
                    "let qs = RXX(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ryy.lf"
                    "RYY(1, q0, q1);"
                    "RYY(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ryyLet.lf"
                    "let qs : [qubit; 2] = RYY(1, q0, q1);"
                    "let qs : [qubit; 2] = RYY(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ryyLetInferred.lf"
                    "let qs = RYY(1, q0, q1);"
                    "let qs = RYY(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rzz.lf"
                    "RZZ(1, q0, q1);"
                    "RZZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rzzLet.lf"
                    "let qs : [qubit; 2] = RZZ(1, q0, q1);"
                    "let qs : [qubit; 2] = RZZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/rzzLetInferred.lf"
                    "let qs = RZZ(1, q0, q1);"
                    "let qs = RZZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ccx.lf"
                    "CCX(q0, q1, q2);"
                    "CCX(q0, q1, q2);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ccxLet.lf"
                    "let qs : [qubit; 3] = CCX(q0, q1, q2);"
                    "let qs : [qubit; 3] = CCX(q0, q1, q2);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ccxLetInferred.lf"
                    "let qs = CCX(q0, q1, q2);"
                    "let qs = CCX(q0, q1, q2);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cswap.lf"
                    "CSWAP(q0, q1, q2);"
                    "CSWAP(q0, q1, q2);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cswapLet.lf"
                    "let qs : [qubit; 3] = CSWAP(q0, q1, q2);"
                    "let qs : [qubit; 3] = CSWAP(q0, q1, q2);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/cswapLetInferred.lf"
                    "let qs = CSWAP(q0, q1, q2);"
                    "let qs = CSWAP(q0, q1, q2);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/gpi.lf"
                    "GPI(1, q);"
                    "GPI(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/gpiLet.lf"
                    "let q : qubit = GPI(1, q);"
                    "let q : qubit = GPI(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/gpiLetInferred.lf"
                    "let q = GPI(1, q);"
                    "let q = GPI(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/gpi2.lf"
                    "GPI2(1, q);"
                    "GPI2(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/gpi2Let.lf"
                    "let q : qubit = GPI2(1, q);"
                    "let q : qubit = GPI2(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/gpi2LetInferred.lf"
                    "let q = GPI2(1, q);"
                    "let q = GPI2(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/ms.lf"
                    "MS(1, 2, q0, q1);"
                    "MS(1, 2, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/msLet.lf"
                    "let qs : [qubit; 2] = MS(1, 2, q0, q1);"
                    "let qs : [qubit; 2] = MS(1, 2, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/msLetInferred.lf"
                    "let qs = MS(1, 2, q0, q1);"
                    "let qs = MS(1, 2, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/zz.lf"
                    "ZZ(1, q0, q1);"
                    "ZZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/zzLet.lf"
                    "let qs : [qubit; 2] = ZZ(1, q0, q1);"
                    "let qs : [qubit; 2] = ZZ(1, q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/zzLetInferred.lf"
                    "let qs = ZZ(1, q0, q1);"
                    "let qs = ZZ(1, q0, q1);"
                    
    -- Test quantum gates declarations corner cases
    runParseOkTest "src/Test/Fixtures/Good/Gates/noSpacesSingleQubitGate.lf"
                    "H(q);"
                    "H(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/extraWhitespaceSingleQubitGate.lf"
                    "SDG(q);"
                    "SDG(q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/noSpacesTwoQubitGate.lf"
                    "CX(q0, q1);"
                    "CX(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/extraWhitespaceTwoQubitGate.lf"
                    "SWAP(q0, q1);"
                    "SWAP(q0, q1);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/noSpacesParametricGate.lf"
                    "RX(1, q);"
                    "RX(1, q);"
    runParseOkTest "src/Test/Fixtures/Good/Gates/extraWhitespaceParametricGate.lf"
                    "CU3(1, 2, 3, q0, q1);"
                    "CU3(1, 2, 3, q0, q1);"

    -- Test invalid quantum gates declarations
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingClosingParenInSingleQubitGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingArgumentSeparatorInSingleQubitGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingCommaInTwoQubitGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingClosingParenInTwoQubitGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingCommaInParametricGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingMiddleParameterInParametricGate.lf"
    runParseShouldFailTest
                    "src/Test/Fixtures/Bad/Gates/missingClosingParenInParametricGate.lf"